---

apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: animals
spec: {}
status: {}

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tiger
  name: tiger
  namespace: animals
spec:
  containers:
  - image: nginx
    name: tiger
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: tiger
  name: tiger
  namespace: animals
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: tiger
status:
  loadBalancer: {}
