---
  
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: cloud
spec: {}
status: {}

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: compute
  name: compute
  namespace: cloud
spec:
  containers:
  - image: nginx
    name: compute
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: storage
  name: storage
  namespace: cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: storage
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: network
  name: network
  namespace: cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: network
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}