apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-pv
  name: pod-pv
spec:
  containers:
  - image: nginx
    name: pod-pv
    volumeMounts:
    - name: cloud-vol
      mountPath: /var/log/nginx
      
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}